version: 0.0.0.{build}
image: Visual Studio 2017

# Only build master branch
branches:
  only:
  - master

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true  # Don't download unneeded packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true        # Don't send telemetry

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
      Install-Module InvokeBuild -MinimumVersion 5.4.0 -Scope CurrentUser -Force | Out-Null

build_script:
  - ps: Invoke-Build
