# Azure DevOps
# Build pipeline for PSRule

displayName: 'PowerShell Module'

strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-16.04'
      benchmark: 'true'
    MacOS:
      imageName: 'macos-10.13'
    Windows:
      imageName: 'vs2017-win2016'
      publishModule: 'true'

variables:
  buildConfiguration: 'Release'
  version: '0.2.0'

# Use build number format, i.e. 0.1.0-B181101
name: $(version)-B$(date:yyMM)$(rev:rr)

trigger:
- master

pool:
  vmImage: $(imageName)

steps:

# Install pipeline dependencies and build module
- powershell: ./scripts/pipeline-build.ps1 -File ./PSRule.build.ps1 -Configuration $(buildConfiguration) -ModuleVersion $(Build.BuildNumber) -ReleaseVersion "$(Release.Version)" -Benchmark:$(benchmark)
  displayName: 'Build module'

# Run module benchmark
- powershell: ./scripts/pipeline-build.ps1 -Task Benchmark -File ./PSRule.build.ps1 -Configuration $(buildConfiguration) -ModuleVersion $(Build.BuildNumber) -ReleaseVersion "$(Release.Version)"
  displayName: 'Benchmark'
  condition: eq(variables['benchmark'], 'true')

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunTitle: 'Pester unit tests'
    testRunner: NUnit
    testResultsFiles: 'reports/*.xml'
    mergeTestResults: true
    configuration: $(buildConfiguration)
  condition: succeededOrFailed()

# Generate artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish PSRule module'
  inputs:
    PathtoPublish: out/modules/PSRule
    ArtifactName: PSRule
  condition: and(succeeded(), eq(variables['publishModule'], 'true'))