# Azure DevOps
# Build pipeline for PSRule

variables:
  buildConfiguration: 'Release'
  version: '0.2.0'

# Use build number format, i.e. 0.1.0-B181101
name: $(version)-B$(date:yyMM)$(rev:rr)

trigger:
- master

pool:
  vmImage: VS2017-Win2016

steps:

# Install pipeline dependencies and build module
- powershell: ./scripts/pipeline-build.ps1 -File ./PSRule.build.ps1 -Configuration $(buildConfiguration) -ModuleVersion $(Build.BuildNumber) -ReleaseVersion "$(Release.Version)"
  displayName: 'Build module'

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunTitle: 'Pester unit tests'
    testRunner: NUnit
    testResultsFiles: 'reports/*.xml'
    mergeTestResults: true
    configuration: $(buildConfiguration)
  condition: succeededOrFailed()

# Generate artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish PSRule module'
  inputs:
    PathtoPublish: out/modules/PSRule
    ArtifactName: PSRule
