# Azure DevOps
# Build pipeline for PSRule

# Use build number format, i.e. 180801
name: $(date:yyMM)$(rev:rr)

trigger:
- master

pool:
  vmImage: VS2017-Win2016

variables:
  buildConfiguration: 'Release'
  version: '0.1.0'

steps:

# Install pipeline dependencies
- powershell: ./scripts/vstsbuild.ps1
  displayName: 'Install Invoke-Build'

# Invoke build
- powershell: Invoke-Build -Configuration $(buildConfiguration) -ModuleVersion $(version) -Revision $(Build.BuildNumber)
  displayName: 'Build module'

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testRunTitle: 'Pester unit tests'
    testResultsFormat: NUnit
    testResultsFiles: 'reports/*.xml'
    mergeTestResults: true
    buildConfiguration: $(buildConfiguration)
  condition: succeededOrFailed()

# Generate artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish PSRule module'
  inputs:
    PathtoPublish: out/modules/PSRule
    ArtifactName: PSRule
