//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormatterStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatterStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRule.Resources.FormatterStrings", typeof(FormatterStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ____  _____ ____        __\n   / __ \/ ___// __ \__  __/ /__\n  / /_/ /\__ \/ /_/ / / / / / _ \\n / ____/___/ / _, _/ /_/ / /  __/\n/_/    /____/_/ |_|\__,_/_/\___/.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | MESSAGE:.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | .
        /// </summary>
        internal static string MessagePrefix {
            get {
                return ResourceManager.GetString("MessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} v{1}.
        /// </summary>
        internal static string ModuleVersion {
            get {
                return ResourceManager.GetString("ModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | POSITION:.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using PSRule v{0}.
        /// </summary>
        internal static string PSRuleVersion {
            get {
                return ResourceManager.GetString("PSRuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | REASON:.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | - .
        /// </summary>
        internal static string ReasonPrefix {
            get {
                return ResourceManager.GetString("ReasonPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | RECOMMEND:.
        /// </summary>
        internal static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | .
        /// </summary>
        internal static string RecommendPrefix {
            get {
                return ResourceManager.GetString("RecommendPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [ERROR] {0}.
        /// </summary>
        internal static string Result_Error {
            get {
                return ResourceManager.GetString("Result_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed {1} with the error &apos;{2}&apos;..
        /// </summary>
        internal static string Result_ErrorDetail {
            get {
                return ResourceManager.GetString("Result_ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [FAIL] {0}.
        /// </summary>
        internal static string Result_Fail {
            get {
                return ResourceManager.GetString("Result_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed {1}. {2}.
        /// </summary>
        internal static string Result_FailDetail {
            get {
                return ResourceManager.GetString("Result_FailDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [PASS] {0}.
        /// </summary>
        internal static string Result_Pass {
            get {
                return ResourceManager.GetString("Result_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     [WARN] {0}.
        /// </summary>
        internal static string Result_Warning {
            get {
                return ResourceManager.GetString("Result_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | STACK TRACE:.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules processed: {0}, failed: {1}, errored: {2}.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
    }
}
