//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PSRuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PSRuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRule.Resources.PSRuleResources", typeof(PSRuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} resource &apos;{1}&apos; is currently referencing &apos;{2}&apos; using the alias &apos;{3}&apos;. Consider updating the reference to use name or id directly..
        /// </summary>
        internal static string AliasReference {
            get {
                return ResourceManager.GetString("AliasReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression for the rule &apos;{0}&apos; was configured using the alias &apos;{1}&apos;. Consider updating the suppression to use the name or id directly..
        /// </summary>
        internal static string AliasSuppression {
            get {
                return ResourceManager.GetString("AliasSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments for &apos;{0}&apos; are not in the expected format or type..
        /// </summary>
        internal static string ArgumentFormatInvalid {
            get {
                return ResourceManager.GetString("ArgumentFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; for &apos;{1}&apos; is not a valid boolean..
        /// </summary>
        internal static string ArgumentInvalidBoolean {
            get {
                return ResourceManager.GetString("ArgumentInvalidBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; for &apos;{1}&apos; is not a valid integer..
        /// </summary>
        internal static string ArgumentInvalidInteger {
            get {
                return ResourceManager.GetString("ArgumentInvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; for &apos;{1}&apos; is not a valid string..
        /// </summary>
        internal static string ArgumentInvalidString {
            get {
                return ResourceManager.GetString("ArgumentInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of arguments &apos;{1}&apos; is not within the allowed range for &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentsOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The baseline &apos;{0}&apos; is obsolete. Consider switching to an alternative baseline..
        /// </summary>
        internal static string BaselineObsolete {
            get {
                return ResourceManager.GetString("BaselineObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding functions are not supported in this language mode..
        /// </summary>
        internal static string ConstrainedTargetBinding {
            get {
                return ResourceManager.GetString("ConstrainedTargetBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The property &apos;${1}.{2}&apos; is obsolete and will be removed in the next major version..
        /// </summary>
        internal static string DebugPropertyObsolete {
            get {
                return ResourceManager.GetString("DebugPropertyObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target failed If precondition.
        /// </summary>
        internal static string DebugTargetIfMismatch {
            get {
                return ResourceManager.GetString("DebugTargetIfMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target failed Rule precondition.
        /// </summary>
        internal static string DebugTargetRuleMismatch {
            get {
                return ResourceManager.GetString("DebugTargetRuleMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target failed sub-selector pre-condition..
        /// </summary>
        internal static string DebugTargetSubselectorMismatch {
            get {
                return ResourceManager.GetString("DebugTargetSubselectorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target failed Type precondition.
        /// </summary>
        internal static string DebugTargetTypeMismatch {
            get {
                return ResourceManager.GetString("DebugTargetTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular rule dependency was detected. The rule &apos;{0}&apos; depends on &apos;{1}&apos; which also depend on &apos;{0}&apos;..
        /// </summary>
        internal static string DependencyCircularReference {
            get {
                return ResourceManager.GetString("DependencyCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency &apos;{0}&apos; for &apos;{1}&apos; could not be found. Check that the rule is defined in a .Rule.ps1 file within the search path..
        /// </summary>
        internal static string DependencyNotFound {
            get {
                return ResourceManager.GetString("DependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &apos;{0}&apos; is deprecated and will be removed with PSRule v3. See http://aka.ms/ps-rule/deprecations for more detail..
        /// </summary>
        internal static string DeprecatedOption {
            get {
                return ResourceManager.GetString("DeprecatedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; is using a duplicate resource identifier. A resource with the identifier &apos;{1}&apos; already exists. Each resource must have a unique name, ref, and aliases. See https://aka.ms/ps-rule/naming for guidance on naming within PSRule..
        /// </summary>
        internal static string DuplicateResourceId {
            get {
                return ResourceManager.GetString("DuplicateResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule with the same name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string DuplicateRuleName {
            get {
                return ResourceManager.GetString("DuplicateRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Reported &apos;{1}&apos;. At {2}:{3} char:{4}.
        /// </summary>
        internal static string ErrorDetailMessage {
            get {
                return ResourceManager.GetString("ErrorDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occured..
        /// </summary>
        internal static string ErrorPipelineException {
            get {
                return ResourceManager.GetString("ErrorPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists: {0}.
        /// </summary>
        internal static string ExistsTrue {
            get {
                return ResourceManager.GetString("ExistsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse expression. The expression may not be valid. Expression: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpressionInvalid {
            get {
                return ResourceManager.GetString("ExpressionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileSourceType {
            get {
                return ResourceManager.GetString("FileSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][D] -- Found {0} PSRule module(s).
        /// </summary>
        internal static string FoundModules {
            get {
                return ResourceManager.GetString("FoundModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function &quot;{0}&quot; was not found..
        /// </summary>
        internal static string FunctionNotFound {
            get {
                return ResourceManager.GetString("FunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language expression index &apos;{0}&apos; is not valid for the object..
        /// </summary>
        internal static string IndexInvalid {
            get {
                return ResourceManager.GetString("IndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output written to the following file: &apos;{0}&apos;.
        /// </summary>
        internal static string InfoOutputPath {
            get {
                return ResourceManager.GetString("InfoOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input path was added: {0}.
        /// </summary>
        internal static string InputAdded {
            get {
                return ResourceManager.GetString("InputAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid ErrorAction ({0}) was specified for rule at {1}. Ignore | Stop are supported..
        /// </summary>
        internal static string InvalidErrorAction {
            get {
                return ResourceManager.GetString("InvalidErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource name &apos;{0}&apos; is not valid at {1}. Each resource name must be between 3-128 characters in length, must start and end with a letter or number, and only contain letters, numbers, hyphens, dots, or underscores. See https://aka.ms/ps-rule/naming for more information..
        /// </summary>
        internal static string InvalidResourceName {
            get {
                return ResourceManager.GetString("InvalidResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; is not an accepted specification for &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidResourceSpecification {
            get {
                return ResourceManager.GetString("InvalidResourceSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule nesting was detected for rule at {0}. Rules must not be nested..
        /// </summary>
        internal static string InvalidRuleNesting {
            get {
                return ResourceManager.GetString("InvalidRuleNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid rule result was returned for {0}. Conditions must return boolean $True or $False..
        /// </summary>
        internal static string InvalidRuleResult {
            get {
                return ResourceManager.GetString("InvalidRuleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; can only be used within a Rule block..
        /// </summary>
        internal static string KeywordConditionScope {
            get {
                return ResourceManager.GetString("KeywordConditionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; can only be used within a Rule block or script precondition..
        /// </summary>
        internal static string KeywordRuleScope {
            get {
                return ResourceManager.GetString("KeywordRuleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; can not be nested in a Rule block..
        /// </summary>
        internal static string KeywordSourceScope {
            get {
                return ResourceManager.GetString("KeywordSourceScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][{0}][Trace] -- {1}: {2}.
        /// </summary>
        internal static string LanguageExpressionTraceP2 {
            get {
                return ResourceManager.GetString("LanguageExpressionTraceP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][{0}][Trace] -- {1}: {2} {1} {3}.
        /// </summary>
        internal static string LanguageExpressionTraceP3 {
            get {
                return ResourceManager.GetString("LanguageExpressionTraceP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open your browser to the following location: {0}.
        /// </summary>
        internal static string LaunchBrowser {
            get {
                return ResourceManager.GetString("LaunchBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard match requires exactly one name..
        /// </summary>
        internal static string MatchSingleName {
            get {
                return ResourceManager.GetString("MatchSingleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches: {0}.
        /// </summary>
        internal static string MatchTrue {
            get {
                return ResourceManager.GetString("MatchTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid module can be found with: Name={0}, Version={1}.
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object &apos;{0}&apos; has not been processed because no matching rules were found..
        /// </summary>
        internal static string ObjectNotProcessed {
            get {
                return ResourceManager.GetString("ObjectNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object path not found..
        /// </summary>
        internal static string ObjectPathNotFound {
            get {
                return ResourceManager.GetString("ObjectPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object path expression reached the maximum depth of {0} evaluating the path &apos;{1}&apos;..
        /// </summary>
        internal static string ObjectPathRecurseMaxDepth {
            get {
                return ResourceManager.GetString("ObjectPathRecurseMaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options file does not exist..
        /// </summary>
        internal static string OptionsNotFound {
            get {
                return ResourceManager.GetString("OptionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Source: {0}.
        /// </summary>
        internal static string OptionsSourceComment {
            get {
                return ResourceManager.GetString("OptionsSourceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string OutcomeError {
            get {
                return ResourceManager.GetString("OutcomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string OutcomeFail {
            get {
                return ResourceManager.GetString("OutcomeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string OutcomePass {
            get {
                return ResourceManager.GetString("OutcomePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FAIL] -- {0}:: Reported for &apos;{1}&apos;.
        /// </summary>
        internal static string OutcomeRuleFail {
            get {
                return ResourceManager.GetString("OutcomeRuleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PASS] -- {0}:: Reported for &apos;{1}&apos;.
        /// </summary>
        internal static string OutcomeRulePass {
            get {
                return ResourceManager.GetString("OutcomeRulePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string OutcomeUnknown {
            get {
                return ResourceManager.GetString("OutcomeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language expression property &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;${0}.{1}&apos; is obsolete and will be removed in the next major version..
        /// </summary>
        internal static string PropertyObsolete {
            get {
                return ResourceManager.GetString("PropertyObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0001: Unable to read options file &apos;{0}&apos;. Please check the file is valid, indented correctly, and encoded as UTF-8. See https://aka.ms/ps-rule/ts-options. {1}.
        /// </summary>
        internal static string PSR0001 {
            get {
                return ResourceManager.GetString("PSR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0002: Summary results are not supported with Job Summaries. See https://aka.ms/ps-rule/troubleshooting-v3.
        /// </summary>
        internal static string PSR0002 {
            get {
                return ResourceManager.GetString("PSR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0003: The specified baseline group &apos;{0}&apos; is not known..
        /// </summary>
        internal static string PSR0003 {
            get {
                return ResourceManager.GetString("PSR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0004: The specified {0} resource &apos;{1}&apos; is not known..
        /// </summary>
        internal static string PSR0004 {
            get {
                return ResourceManager.GetString("PSR0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0005: The {0} &apos;{1}&apos; is obsolete..
        /// </summary>
        internal static string PSR0005 {
            get {
                return ResourceManager.GetString("PSR0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0006: Failed to deserialize the file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string PSR0006 {
            get {
                return ResourceManager.GetString("PSR0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0007: The resource &apos;{0}&apos; using API &apos;{1}&apos; is not recognized as a valid PSRule resource (source: {2})..
        /// </summary>
        internal static string PSR0007 {
            get {
                return ResourceManager.GetString("PSR0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0008: The capability &apos;{0}&apos; requested by the workspace is disabled..
        /// </summary>
        internal static string PSR0008 {
            get {
                return ResourceManager.GetString("PSR0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0009: The capability &apos;{0}&apos; requested by the workspace is not supported..
        /// </summary>
        internal static string PSR0009 {
            get {
                return ResourceManager.GetString("PSR0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0010: The capability &apos;{0}&apos; requested by the module &apos;{1}&apos; is disabled..
        /// </summary>
        internal static string PSR0010 {
            get {
                return ResourceManager.GetString("PSR0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0011: The capability &apos;{0}&apos; requested by the module &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string PSR0011 {
            get {
                return ResourceManager.GetString("PSR0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0012: Added emitter &apos;{0}&apos; to scope &apos;{1}&apos;..
        /// </summary>
        internal static string PSR0012 {
            get {
                return ResourceManager.GetString("PSR0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0013: Completed building chain using &apos;{0}&apos; emitters..
        /// </summary>
        internal static string PSR0013 {
            get {
                return ResourceManager.GetString("PSR0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0014: Failed to create runtime factory &apos;{0}&apos; from &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string PSR0014 {
            get {
                return ResourceManager.GetString("PSR0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0015: No valid sources were found. Please check your working path and configured options. See https://aka.ms/ps-rule/troubleshooting-v3.
        /// </summary>
        internal static string PSR0015 {
            get {
                return ResourceManager.GetString("PSR0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0016: Could not find a matching rule. Please check that Path, Name, and Tag parameters are correct. See https://aka.ms/ps-rule/troubleshooting-v3.
        /// </summary>
        internal static string PSR0016 {
            get {
                return ResourceManager.GetString("PSR0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0017: No valid input objects or files were found. Please check your working path and configured options. See https://aka.ms/ps-rule/troubleshooting-v3.
        /// </summary>
        internal static string PSR0017 {
            get {
                return ResourceManager.GetString("PSR0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSR0022: Language scope not found. See https://aka.ms/ps-rule/troubleshooting-v3.
        /// </summary>
        internal static string PSR0022 {
            get {
                return ResourceManager.GetString("PSR0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize the file &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ReadFileFailed {
            get {
                return ResourceManager.GetString("ReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the path &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ReadInputFailed {
            get {
                return ResourceManager.GetString("ReadInputFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read JSON failed..
        /// </summary>
        internal static string ReadJsonFailed {
            get {
                return ResourceManager.GetString("ReadJsonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module version &apos;{1}&apos; for &apos;{0}&apos; does not match the required version &apos;{2}&apos;. To continue, first update the module to match the version requirement..
        /// </summary>
        internal static string RequiredVersionMismatch {
            get {
                return ResourceManager.GetString("RequiredVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rule/s were suppressed for &apos;{1}&apos;..
        /// </summary>
        internal static string RuleCountSuppressed {
            get {
                return ResourceManager.GetString("RuleCountSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more rules reported errors..
        /// </summary>
        internal static string RuleErrorPipelineException {
            get {
                return ResourceManager.GetString("RuleErrorPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; was excluded from run..
        /// </summary>
        internal static string RuleExcluded {
            get {
                return ResourceManager.GetString("RuleExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more rules reported failure..
        /// </summary>
        internal static string RuleFailPipelineException {
            get {
                return ResourceManager.GetString("RuleFailPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive result reported for &apos;{1}&apos; @{0}..
        /// </summary>
        internal static string RuleInconclusive {
            get {
                return ResourceManager.GetString("RuleInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][R][Trace] -- {0}.
        /// </summary>
        internal static string RuleMatchTrace {
            get {
                return ResourceManager.GetString("RuleMatchTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find required rule definition parameter &apos;{0}&apos; on rule at {1}..
        /// </summary>
        internal static string RuleParameterNotFound {
            get {
                return ResourceManager.GetString("RuleParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at Rule &apos;{0}&apos;, {1}: line {2}.
        /// </summary>
        internal static string RuleStackTrace {
            get {
                return ResourceManager.GetString("RuleStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; was suppressed for &apos;{1}&apos;..
        /// </summary>
        internal static string RuleSuppressed {
            get {
                return ResourceManager.GetString("RuleSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; was suppressed by suppression group &apos;{1}&apos; for &apos;{2}&apos;..
        /// </summary>
        internal static string RuleSuppressionGroup {
            get {
                return ResourceManager.GetString("RuleSuppressionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rule/s were suppressed by suppression group &apos;{1}&apos; for &apos;{2}&apos;..
        /// </summary>
        internal static string RuleSuppressionGroupCount {
            get {
                return ResourceManager.GetString("RuleSuppressionGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &apos;{0}&apos; was suppressed by suppression group &apos;{1}&apos; for &apos;{2}&apos;. {3}.
        /// </summary>
        internal static string RuleSuppressionGroupExtended {
            get {
                return ResourceManager.GetString("RuleSuppressionGroupExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rule/s were suppressed by suppression group &apos;{1}&apos; for &apos;{2}&apos;. {3}.
        /// </summary>
        internal static string RuleSuppressionGroupExtendedCount {
            get {
                return ResourceManager.GetString("RuleSuppressionGroupExtendedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][D] -- Scanning for source files in module: {0}.
        /// </summary>
        internal static string ScanModule {
            get {
                return ResourceManager.GetString("ScanModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][D] -- Scanning for source files: {0}.
        /// </summary>
        internal static string ScanSource {
            get {
                return ResourceManager.GetString("ScanSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script was not found..
        /// </summary>
        internal static string ScriptNotFound {
            get {
                return ResourceManager.GetString("ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PSRule][S][Trace] -- {0}.
        /// </summary>
        internal static string SelectorMatchTrace {
            get {
                return ResourceManager.GetString("SelectorMatchTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not serialize a null PSObject..
        /// </summary>
        internal static string SerializeNullPSObject {
            get {
                return ResourceManager.GetString("SerializeNullPSObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create path.
        /// </summary>
        internal static string ShouldCreatePath {
            get {
                return ResourceManager.GetString("ShouldCreatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write file.
        /// </summary>
        internal static string ShouldWriteFile {
            get {
                return ResourceManager.GetString("ShouldWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source was not found..
        /// </summary>
        internal static string SourceNotFound {
            get {
                return ResourceManager.GetString("SourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression group &apos;{0}&apos; has expired and will be ignored..
        /// </summary>
        internal static string SuppressionGroupExpired {
            get {
                return ResourceManager.GetString("SuppressionGroupExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using changed files: {0}.
        /// </summary>
        internal static string UsingChangedFile {
            get {
                return ResourceManager.GetString("UsingChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using invariant culture may cause rule infomation to be displayed incorrectly. Consider using -Culture or set the Output.Culture option..
        /// </summary>
        internal static string UsingInvariantCulture {
            get {
                return ResourceManager.GetString("UsingInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;${0}&apos; can only be used within a Rule block..
        /// </summary>
        internal static string VariableConditionScope {
            get {
                return ResourceManager.GetString("VariableConditionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version constraint &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string VersionConstraintInvalid {
            get {
                return ResourceManager.GetString("VersionConstraintInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Within parameter Value must be a string when the Like parameter is used..
        /// </summary>
        internal static string WithinLikeNotString {
            get {
                return ResourceManager.GetString("WithinLikeNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within: {0}.
        /// </summary>
        internal static string WithinTrue {
            get {
                return ResourceManager.GetString("WithinTrue", resourceCulture);
            }
        }
    }
}
