//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReasonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReasonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRule.Resources.ReasonStrings", typeof(ReasonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; contains &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_Contains {
            get {
                return ResourceManager.GetString("Assert_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not match the expression &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_DoesNotMatch {
            get {
                return ResourceManager.GetString("Assert_DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; ends with &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_EndsWith {
            get {
                return ResourceManager.GetString("Assert_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not contain only lowercase characters..
        /// </summary>
        internal static string Assert_IsLower {
            get {
                return ResourceManager.GetString("Assert_IsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null or empty..
        /// </summary>
        internal static string Assert_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Assert_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is set to &apos;{0}&apos;..
        /// </summary>
        internal static string Assert_IsSetTo {
            get {
                return ResourceManager.GetString("Assert_IsSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not contain only uppercase characters..
        /// </summary>
        internal static string Assert_IsUpper {
            get {
                return ResourceManager.GetString("Assert_IsUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is like &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_Like {
            get {
                return ResourceManager.GetString("Assert_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; matches the expression &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_Matches {
            get {
                return ResourceManager.GetString("Assert_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not an array..
        /// </summary>
        internal static string Assert_NotArray {
            get {
                return ResourceManager.GetString("Assert_NotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a boolean..
        /// </summary>
        internal static string Assert_NotBoolean {
            get {
                return ResourceManager.GetString("Assert_NotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not {1} {2}..
        /// </summary>
        internal static string Assert_NotComparedTo {
            get {
                return ResourceManager.GetString("Assert_NotComparedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not contain any of {1}..
        /// </summary>
        internal static string Assert_NotContains {
            get {
                return ResourceManager.GetString("Assert_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a date..
        /// </summary>
        internal static string Assert_NotDateTime {
            get {
                return ResourceManager.GetString("Assert_NotDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not end with any of {1}..
        /// </summary>
        internal static string Assert_NotEndsWith {
            get {
                return ResourceManager.GetString("Assert_NotEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not in {1}..
        /// </summary>
        internal static string Assert_NotInSet {
            get {
                return ResourceManager.GetString("Assert_NotInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not an integer..
        /// </summary>
        internal static string Assert_NotInteger {
            get {
                return ResourceManager.GetString("Assert_NotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not like &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_NotLike {
            get {
                return ResourceManager.GetString("Assert_NotLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not numeric..
        /// </summary>
        internal static string Assert_NotNumeric {
            get {
                return ResourceManager.GetString("Assert_NotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the specified schemas match &apos;{0}&apos;..
        /// </summary>
        internal static string Assert_NotSpecifiedSchema {
            get {
                return ResourceManager.GetString("Assert_NotSpecifiedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not start with any of {1}..
        /// </summary>
        internal static string Assert_NotStartsWith {
            get {
                return ResourceManager.GetString("Assert_NotStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a string..
        /// </summary>
        internal static string Assert_NotString {
            get {
                return ResourceManager.GetString("Assert_NotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; starts with &apos;{1}&apos;..
        /// </summary>
        internal static string Assert_StartsWith {
            get {
                return ResourceManager.GetString("Assert_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; can not be compared with &apos;{1}&apos;..
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not contain &apos;{1}&apos;..
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; has &apos;{1}&apos; items instead of &apos;{2}&apos;..
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not end with &apos;{1}&apos;..
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the field(s) existed: {0}.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field(s) existed: {0}.
        /// </summary>
        internal static string ExistsNot {
            get {
                return ResourceManager.GetString("ExistsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header was not set..
        /// </summary>
        internal static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not &gt; &apos;{1}&apos;..
        /// </summary>
        internal static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not &gt;= &apos;{1}&apos;..
        /// </summary>
        internal static string GreaterOrEqual {
            get {
                return ResourceManager.GetString("GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is set to &apos;{1}&apos;..
        /// </summary>
        internal static string HasExpectedFieldValue {
            get {
                return ResourceManager.GetString("HasExpectedFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; exists..
        /// </summary>
        internal static string HasField {
            get {
                return ResourceManager.GetString("HasField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the specified schemas match &apos;{0}&apos;..
        /// </summary>
        internal static string HasJsonSchema {
            get {
                return ResourceManager.GetString("HasJsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; was not included in the set..
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; does not contain only letters..
        /// </summary>
        internal static string IsLetter {
            get {
                return ResourceManager.GetString("IsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed schema validation on {0}. {1}.
        /// </summary>
        internal static string JsonSchemaInvalid {
            get {
                return ResourceManager.GetString("JsonSchemaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON schema &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string JsonSchemaNotFound {
            get {
                return ResourceManager.GetString("JsonSchemaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not &lt; &apos;{1}&apos;..
        /// </summary>
        internal static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not &lt;= &apos;{1}&apos;..
        /// </summary>
        internal static string LessOrEqual {
            get {
                return ResourceManager.GetString("LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the regex(s) matched: {0}.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regex &apos;{0}&apos; matched..
        /// </summary>
        internal static string MatchNot {
            get {
                return ResourceManager.GetString("MatchNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; does not match the pattern &apos;{1}&apos;..
        /// </summary>
        internal static string MatchPattern {
            get {
                return ResourceManager.GetString("MatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; has &apos;{1}&apos; items instead of not &apos;{2}&apos;..
        /// </summary>
        internal static string NotCount {
            get {
                return ResourceManager.GetString("NotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is not enumerable..
        /// </summary>
        internal static string NotEnumerable {
            get {
                return ResourceManager.GetString("NotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string NotHasField {
            get {
                return ResourceManager.GetString("NotHasField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string NotHasFieldValue {
            get {
                return ResourceManager.GetString("NotHasFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; was in the set..
        /// </summary>
        internal static string NotIn {
            get {
                return ResourceManager.GetString("NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; matches the pattern &apos;{1}&apos;..
        /// </summary>
        internal static string NotMatchPattern {
            get {
                return ResourceManager.GetString("NotMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; is not null..
        /// </summary>
        internal static string NotNull {
            get {
                return ResourceManager.GetString("NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is within the path &apos;{1}&apos;..
        /// </summary>
        internal static string NotWithinPath {
            get {
                return ResourceManager.GetString("NotWithinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; is null..
        /// </summary>
        internal static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is not empty..
        /// </summary>
        internal static string NullOrEmpty {
            get {
                return ResourceManager.GetString("NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string NullOrEmptyParameter {
            get {
                return ResourceManager.GetString("NullOrEmptyParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is null..
        /// </summary>
        internal static string NullParameter {
            get {
                return ResourceManager.GetString("NullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were provided..
        /// </summary>
        internal static string ResultsNotProvided {
            get {
                return ResourceManager.GetString("ResultsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; does not start with &apos;{1}&apos;..
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; is not a string..
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; did not contain &apos;{1}&apos;..
        /// </summary>
        internal static string Subset {
            get {
                return ResourceManager.GetString("Subset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; included multiple instances of &apos;{1}&apos;..
        /// </summary>
        internal static string SubsetDuplicate {
            get {
                return ResourceManager.GetString("SubsetDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{2}&apos; of type {1} is not {0}..
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{1}&apos; of type {0} is not an integer..
        /// </summary>
        internal static string TypeInteger {
            get {
                return ResourceManager.GetString("TypeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{1}&apos; of type {0} is not numeric..
        /// </summary>
        internal static string TypeNumeric {
            get {
                return ResourceManager.GetString("TypeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the type name(s) match: {0}.
        /// </summary>
        internal static string TypeOf {
            get {
                return ResourceManager.GetString("TypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value &apos;{0}&apos; is not a version string..
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version &apos;{0}&apos; does not match the constraint &apos;{1}&apos;..
        /// </summary>
        internal static string VersionContraint {
            get {
                return ResourceManager.GetString("VersionContraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field value didn&apos;t match the set..
        /// </summary>
        internal static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was within the set..
        /// </summary>
        internal static string WithinNot {
            get {
                return ResourceManager.GetString("WithinNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not within the path &apos;{1}&apos;..
        /// </summary>
        internal static string WithinPath {
            get {
                return ResourceManager.GetString("WithinPath", resourceCulture);
            }
        }
    }
}
