//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Summaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSRule.Resources.Summaries", typeof(Summaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string JobSummary_Analysis {
            get {
                return ResourceManager.GetString("JobSummary_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis did not return any failing or erroring results..
        /// </summary>
        internal static string JobSummary_AnalysisEmpty {
            get {
                return ResourceManager.GetString("JobSummary_AnalysisEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following results were reported with fail or error results..
        /// </summary>
        internal static string JobSummary_AnalysisResults {
            get {
                return ResourceManager.GetString("JobSummary_AnalysisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} PSRule completed with an overall result of &apos;{1}&apos; with {2} rule(s) and {3} target(s) in {4}..
        /// </summary>
        internal static string JobSummary_FinalResultMessage {
            get {
                return ResourceManager.GetString("JobSummary_FinalResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following modules where included in analysis..
        /// </summary>
        internal static string JobSummary_IncludedModules {
            get {
                return ResourceManager.GetString("JobSummary_IncludedModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string JobSummary_Module {
            get {
                return ResourceManager.GetString("JobSummary_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string JobSummary_Name {
            get {
                return ResourceManager.GetString("JobSummary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string JobSummary_Source {
            get {
                return ResourceManager.GetString("JobSummary_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synopsis.
        /// </summary>
        internal static string JobSummary_Synopsis {
            get {
                return ResourceManager.GetString("JobSummary_Synopsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name.
        /// </summary>
        internal static string JobSummary_TargetName {
            get {
                return ResourceManager.GetString("JobSummary_TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSRule result summary.
        /// </summary>
        internal static string JobSummary_Title {
            get {
                return ResourceManager.GetString("JobSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string JobSummary_Version {
            get {
                return ResourceManager.GetString("JobSummary_Version", resourceCulture);
            }
        }
    }
}
