
---
# Synopsis: Example module configuration for Enterprise.Rules module
kind: ModuleConfig
metadata:
  name: Enterprise.Rules
spec:
  binding:
    targetName:
    - ResourceName
    - FullName
    - name
    targetType:
    - ResourceType
    - type
    - Extension
    field:
      resourceId: [ 'ResourceId' ]
      subscriptionId: [ 'SubscriptionId' ]
      resourceGroupName: [ 'ResourceGroupName' ]
