// This file is auto-generated by the build system.
// Do not edit this file directly.

namespace PSRule;

/// <summary>
/// The PSRule engine (generated).
/// </summary>
public static partial class Engine
{
    private static readonly string _Version = "0.0.1-dev";
}