// <auto-generated/>
// This file provides version info generated during build.

namespace PSRule
{
    public static partial class Engine
    {
        private const string _Version = "0.0.1";
    }
}