// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// <auto-generated/>
namespace PSRule
{
    public static partial class Engine
    {
        private const string _Version = "3.0.0-dev";
    }
}