name: Feature request
description: Suggest an idea
title: '[FEATURE] <title>'
type: Feature
labels: ['Needs: Triage :mag:']
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Your suggestion
      description: A clear and concise description of the solution or improvement you would like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
