# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Visual Studio Code image with .NET

# NOTE:
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/dotnet/.devcontainer/base.Dockerfile

ARG VARIANT="6.0-bullseye-slim"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-${VARIANT}
