#
# Stale item management
#

# NOTES:
# This workflow greets a person for their a first issue or PR.

name: First interaction

on: [pull_request_target, issues]

permissions: {}

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: 'Thanks for raising your first issue, the team appreciates the time you have taken 😉'
          pr_message: 'Thank you for your contribution, one of the team will evaluate shortly.'
